### ISSUE TITLE
Negative income

### ISSUE THREAD

**Issue by topongo** [matteobregola/DatabaseInitialization#1]
Almost every movie have a negative net income. Because the budget is always lesser than the gross income. Maybe I'll open a pull request with the correct data.

**Comment by topongo** [comment]
There's another problem: if I try to increase the budget, let's say, multiply it by 10, we incur in a overflow error, so postgres won't let me do it, the orther option is to keep the `gross` and `budget` fields as dollars and not as cents of dollars. So:
```sql
UPDATE Movies set gross=(gross / 100), budget=(budget / 100);
# and then multiply it by 10
UPDATE Movies set gross=(gross * 10);
```
Or do it in a single line
```sql
UPDATE Movies set gross=(gross / 10), budget=(budget / 100);
```

Edit:
dividing by 100 the budget is not enough, we need to keep the `gross` as is, so 
```sql
UPDATE Movies set budget=(budget / 100);
```

**Comment by matteobregola** [comment]
Good point, as i said in the readme, unfortunately i randomized the budget because i didn't find the correct values. 
In the original query there was only 27 film where gross > budget. 
So i added the query you suggested in Database_Init.txt and Database_Schema.sql:
`UPDATE Movies set budget=(budget / 100);` 

Now there are 260 movies where gross > budget. This is more "realistic" even if we need to consider that the "budget" is not actually the money spent; the film could have a positive net income even if gross<budget.

Thanks for the suggestion!
